---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shtl-ink-storage-class
  namespace: shtl-ink
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"