---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shtl-ink-db-claim
  namespace: shtl-ink
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: shtl-ink-storage-class
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shtl-ink
  name: shtl-ink-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "shtl-ink-db"
  template:
    metadata:
      labels:
        app: shtl-ink-db
    spec:
      hostname: shtl-ink-db
      volumes:
        - name: database-ebs
          persistentVolumeClaim:
            claimName: shtl-ink-db-claim
      initContainers:
        - name: volume-dirs-init-cntr
          image: busybox:1.35
          command:
            - "/bin/mkdir"
          args:
            - "-p"
            - "/db/data"
          volumeMounts:
            - name: database-ebs
              mountPath: "/db"
      containers:
        - name: shtl-ink-db
          image: postgres:latest
          env:
            - name: PG_TRUST_LOCALNET
              value: "true"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shtl-ink-secrets
                  key: db-user
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shtl-ink-secrets
                  key: db-pass
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: shtl-ink-secrets
                  key: db-name
                  optional: false
          ports:
            - name: pod-db-port
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: database-ebs
              mountPath: /var/lib/postgresql/data
              subPath: data