---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shtl-ink-storage-class
  namespace: shtl-ink
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"